#!/usr/bin/env bash
# a Bash script that will display information about subdomains
# shellcheck disable=SC2086
getSubdomaininfo () {
if [ $# -eq 2 ]
then
    subdomain="$2"
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain '$subdomain' is a "$4" record and points to "$NF""}'

elif [ $# -eq 1 ]
then
    subdomains=('www' 'lb-01' 'web-01' 'web-02')
    for each in "${subdomains[@]}"
    do
        dig $each.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print "The subdomain '$each' is a "$4" record and points to "$NF""}'
    done
fi
}
getSubdomaininfo $1 $2
