#!/usr/bin/env bash
# thi script copies a file from local machine to remote machine using ssh key
if [ "$#" -lt 3 ] ;then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3"@"$2":~
fi
