#!/usr/bin/env bash
# install nginx in the server and create a file with Hello World! 
# nginx should be listening to port 80
apt-get -y update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start