#!/usr/bin/env bash
# shellcheck disable=SC2154
# install nginx in the server and create a file with Hello World! 
# nginx should be listening to port 80
apt-get -y update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html/
echo "Hello World!" > /var/www/html/index.nginx-debian.html
ufw allow 'Nginx HTTP'

# redirection
mystr="\n\tlocation = \/redirect_me\/ \{\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 \; \n\t\}"
replace="server {"
sed -i "0,/$replace/{s/$replace/$replace$mystr/}" /etc/nginx/sites-available/default

# page error 404
echo "Ceci n'est pas une page" > /var/www/html/404.html
mystr="\n\terror_page 404 \/404.html\;\n\tlocation = \/404.html \{\n\t\troot \/var\/www\/html\; \n\t\tinternal\;\n\t\}"
replace="server {"
sed -i "0,/$replace/{s/$replace/$replace$mystr/}" /etc/nginx/sites-available/default

# add custom header containing server hostname
mystr="\n\tadd_header X-Served-By $HOSTNAME;"
replace="http {"
sudo sed -i "0,/$replace/{s/$replace/$replace$mystr/}" /etc/nginx/nginx.conf

# finally start nginx
service nginx start
