#!/usr/bin/env bash
# debug an nginx server not responding to port 80
mystr="\n\tlisten 80 default_server\;\n\tlisten [::]:80 default_server\;"
replace="server {"
sed -i "0,/$replace/{s/$replace/$replace$mystr/}" /etc/nginx/sites-available/default
service nginx start
