#!/usr/bin/env bash
# debug an nginx server not responding to port 80
mystr="80 default_server\;"
replace="8080 default_server\;"
sed -i "{s/$replace/$mystr/}" /etc/nginx/sites-available/default
service nginx start
