#!/usr/bin/env bash
# debug an nginx server not responding to port 80
sed -i "{s/8080 default_server/80 default_server/}" /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
